# Generated by Django 6.0.5 on 2026-07-09 20:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('theaters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('duration_minutes', models.PositiveSmallIntegerField()),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters/')),
                ('cover', models.ImageField(blank=True, help_text='Immagine di copertina dello spettacolo', null=True, upload_to='covers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shows', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shows', to='shows.category')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending_artist_confirmation', 'Pending artist confirmation'), ('scheduled', 'Scheduled'), ('cancelled', 'Cancelled')], default='pending_artist_confirmation', max_length=32)),
                ('confirmed_by_artist', models.BooleanField(default=False)),
                ('confirmed_by_artist_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auditorium', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='performances', to='theaters.auditorium')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='shows.show')),
            ],
            options={
                'ordering': ['starts_at'],
            },
        ),
        migrations.CreateModel(
            name='PerformancePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)])),
                ('auditorium_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_prices', to='theaters.auditoriumzone')),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_prices', to='shows.performance')),
            ],
            options={
                'ordering': ['auditorium_zone__cod_zone'],
                'unique_together': {('performance', 'auditorium_zone')},
            },
        ),
    ]
