# Generated by Django 6.0.5 on 2026-05-11 16:59

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models

ZONE_CHOICES = [
    ("platea", "Platea"),
    ("galleria", "Galleria"),
    ("balconata", "Balconata"),
]

ZONE_MULTIPLIERS = {
    "platea": Decimal("1.00"),
    "galleria": Decimal("0.85"),
    "balconata": Decimal("0.70"),
}


def create_zone_prices(apps, schema_editor):
    Performance = apps.get_model("shows", "Performance")
    PerformanceZonePrice = apps.get_model("shows", "PerformanceZonePrice")
    for performance in Performance.objects.all():
        for zone, _label in ZONE_CHOICES:
            multiplier = ZONE_MULTIPLIERS.get(zone, Decimal("1.00"))
            price = (performance.base_price * multiplier).quantize(Decimal("0.01"))
            PerformanceZonePrice.objects.get_or_create(
                performance=performance,
                zone=zone,
                defaults={"price": price},
            )


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceZonePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(choices=[('platea', 'Platea'), ('galleria', 'Galleria'), ('balconata', 'Balconata')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_prices', to='shows.performance')),
            ],
            options={
                'ordering': ['zone'],
                'unique_together': {('performance', 'zone')},
            },
        ),
        migrations.RunPython(create_zone_prices, migrations.RunPython.noop),
    ]
