# Generated by Django 6.0.5 on 2026-05-11 22:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0002_performancezoneprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='base_price',
            field=models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='performancezoneprice',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='performancezoneprice',
            name='zone',
            field=models.CharField(choices=[('platea', 'Platea'), ('galleria', 'Galleria'), ('loggione', 'Loggione'), ('balconata', 'Balconata'), ('laterale', 'Laterale'), ('vip', 'VIP')], default='platea', max_length=20),
        ),
    ]
