# Generated by Django 6.0.5 on 2026-05-12 07:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0003_alter_performance_base_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='artists',
            field=models.ManyToManyField(related_name='performances_as_artist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='show',
            name='cover',
            field=models.ImageField(blank=True, help_text='Immagine di copertina dello spettacolo', null=True, upload_to='covers/'),
        ),
    ]
