# Generated by Django 6.0.5 on 2026-07-09 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditorium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_auditorium', models.PositiveIntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('seat_rows', models.PositiveSmallIntegerField(default=0)),
                ('seat_cols', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='theaters/')),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=120)),
                ('province', models.CharField(blank=True, max_length=40)),
                ('postal_code', models.CharField(blank=True, max_length=10)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('opening_hours', models.CharField(blank=True, max_length=200)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditoriumZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_zone', models.PositiveIntegerField(blank=True, null=True)),
                ('zone', models.CharField(max_length=50)),
                ('rows', models.PositiveSmallIntegerField(default=4)),
                ('seats_per_row', models.PositiveSmallIntegerField(default=10)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auditorium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='theaters.auditorium')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('auditorium', 'cod_zone')},
            },
        ),
        migrations.AddField(
            model_name='auditorium',
            name='theater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditoriums', to='theaters.theater'),
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.CharField(max_length=2)),
                ('number', models.PositiveSmallIntegerField()),
                ('is_accessible', models.BooleanField(default=False)),
                ('auditorium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='theaters.auditorium')),
                ('auditorium_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='theaters.auditoriumzone')),
            ],
            options={
                'unique_together': {('auditorium', 'row', 'number')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='auditorium',
            unique_together={('theater', 'cod_auditorium')},
        ),
        migrations.CreateModel(
            name='TheaterAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='theaters.theater')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('theater', 'user')},
            },
        ),
    ]
