# Generated by Django 6.0.5 on 2026-05-11 16:59

import string

from django.db import migrations, models


def _zone_for_row(row_index, rows):
    if rows <= 0:
        return "platea"
    fraction = (row_index + 1) / rows
    if fraction <= 0.4:
        return "platea"
    if fraction <= 0.75:
        return "galleria"
    return "balconata"


def assign_zones(apps, schema_editor):
    Hall = apps.get_model("theaters", "Hall")
    Seat = apps.get_model("theaters", "Seat")
    for hall in Hall.objects.all():
        rows = min(hall.seat_rows, len(string.ascii_uppercase))
        for seat in Seat.objects.filter(hall=hall):
            try:
                row_index = string.ascii_uppercase.index(seat.row)
            except ValueError:
                row_index = 0
            seat.zone = _zone_for_row(row_index, rows)
            seat.save(update_fields=["zone"])


class Migration(migrations.Migration):

    dependencies = [
        ('theaters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='zone',
            field=models.CharField(choices=[('platea', 'Platea'), ('galleria', 'Galleria'), ('balconata', 'Balconata')], default='platea', max_length=20),
        ),
        migrations.RunPython(assign_zones, migrations.RunPython.noop),
    ]
