# Generated by Django 6.0.5 on 2026-05-11 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theaters', '0002_seat_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='zone',
            field=models.CharField(choices=[('platea', 'Platea'), ('galleria', 'Galleria'), ('loggione', 'Loggione'), ('balconata', 'Balconata'), ('laterale', 'Laterale'), ('vip', 'VIP')], default='platea', max_length=20),
        ),
        migrations.CreateModel(
            name='HallZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(choices=[('platea', 'Platea'), ('galleria', 'Galleria'), ('loggione', 'Loggione'), ('balconata', 'Balconata'), ('laterale', 'Laterale'), ('vip', 'VIP')], max_length=20)),
                ('rows', models.PositiveSmallIntegerField(default=4)),
                ('seats_per_row', models.PositiveSmallIntegerField(default=10)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='theaters.hall')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
