# Generated by Django 6.0.5 on 2026-05-11 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theaters', '0003_alter_seat_zone_hallzone'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hallzone',
            unique_together={('hall', 'zone')},
        ),
    ]
